baseurl = "conorclaffey.com/"
title = "Conor Claffey"
theme = "cc"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[permalinks]
photography = "/photography/:title/"

[params]
  title1 = "CONOR"
  title2 = "CLAFFEY"
  # blue, green, pink (default), red, sea, viofirelet
  style = "green"
  description = ""
  # copyright = "&copy;2017 Conor Claffey"
  sidebarAbout = [
    ""
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Illustrations"
  url = "illustrations"

  [[params.navlinks]]
  name = "Photography"
  url = "photography"

  [[params.navlinks]]
  name = "Projects"
  url = "projects"

  [[params.navlinks]]
  name = "Posters"
  url = "posters"

  [[params.navlinks]]
  name = "Work"
  url = "work"

  [[params.navlinks]]
  name = "Home"
  url = ""

  [params.social]
  facebook      = ""
  googleplus    = ""
  email         = "conorclaffey65@gmail.com"
  twitter       = ""
  # linkedin      = "full profile url in linkedin"
  stackoverflow = ""
  # instagram     = "full profile url in instagram"
  github        = ""
