baseurl = "localhost:1313"
title = "Conor Claffey"
theme = "cc"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""

[params]
  title1 = "CONOR"
  title2 = "CLAFFEY"
  # blue, green, pink (default), red, sea, violet
  style = "green"
  description = ""
  # copyright = "&copy;2016 Conor Claffey"
  sidebarAbout = [
    ""
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Illustrations"
  url = "categories/illustrations/"

  [[params.navlinks]]
  name = "Photography"
  url = "categories/photography"

  [[params.navlinks]]
  name = "Projects"
  url = "categories/projects"

  [[params.navlinks]]
  name = "Posters"
  url = "categories/posters"

  [[params.navlinks]]
  name = "Work"
url = "categories/work"

  [params.social]
  facebook      = ""
  googleplus    = ""
  email         = "conorclaffey65@gmail.com"
  twitter       = ""
  # linkedin      = "full profile url in linkedin"
  stackoverflow = ""
  # instagram     = "full profile url in instagram"
  github        = ""
